
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw-vllm-openai.serviceAccountName" . }}
  labels:
    {{- include "openclaw-vllm-openai.labels" . | nindent 4 }}
{{- end -}}
